# Trabalho Final - notebook base do projeto da Ana Carolina

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

## Pergunta de pesquisa

#### **Quais características são mais comuns nos acidentes graves e fatais?**

(causa do acidente, tipo de acidente, fase do dia, condição meteorológica)

--- Breve explicação do problema, qual conjunto de dados será utilizado e o que se pretende estudar/avaliar no trabalho.

In [2]:
df = pd.read_csv("../datasets/ana_carolina/datatran2017-2024.zip", compression='zip', encoding='latin-1', sep=';')

df.head()

,id,data_inversa,dia_semana,horario,uf,br,km,municipio,causa_acidente,tipo_acidente,...,feridos_graves,ilesos,ignorados,feridos,veiculos,latitude,longitude,regional,delegacia,uop
0,17,01/01/2017,domingo,01:45:00,RS,116,"34,9",VACARIA,Defeito Mecânico no Veículo,Colisão traseira,...,0,2,0,4,2,"-28,5071196","-50,941176",SPRF-RS,DEL05-RS,UOP03-DEL05-RS
1,20,01/01/2017,domingo,01:00:00,PR,376,636,TIJUCAS DO SUL,Velocidade Incompatível,Saída de leito carroçável,...,0,1,0,0,2,"-25,754","-49,1266",SPRF-PR,DEL01-PR,DEL7/1-UOP08/PR
2,69,01/01/2017,domingo,04:40:00,BA,101,65,ENTRE RIOS,Condutor Dormindo,Colisão frontal,...,1,2,0,2,2,"-11,9618","-38,0953",SPRF-BA,DEL01-BA,UOP04-DEL01-BA
3,106,01/01/2017,domingo,06:30:00,PA,316,"72,5",CASTANHAL,Falta de Atenção à Condução,Colisão lateral,...,0,3,0,0,3,"-1,2899799","-47,83483207",SPRF-PA,DEL01-PA,DEL19/1-UOP02/PA
4,109,01/01/2017,domingo,09:00:00,GO,20,"220,5",POSSE,Defeito na Via,Colisão com objeto estático,...,1,0,1,3,2,"-14,14220931","-46,32258922",SPRF-DF,DEL02-DF,UOP03-DEL02-DF

In [3]:
df.columns

Index(['id', 'data_inversa', 'dia_semana', 'horario', 'uf', 'br', 'km',
       'municipio', 'causa_acidente', 'tipo_acidente',
       'classificacao_acidente', 'fase_dia', 'sentido_via',
       'condicao_metereologica', 'tipo_pista', 'tracado_via', 'uso_solo',
       'pessoas', 'mortos', 'feridos_leves', 'feridos_graves', 'ilesos',
       'ignorados', 'feridos', 'veiculos', 'latitude', 'longitude', 'regional',
       'delegacia', 'uop'],
      dtype='str')

## Classificação das variáveis associadas à pergunta de pesquisa

In [4]:
df["causa_acidente"].unique()

<StringArray>
[                                                   'Defeito Mecânico no Veículo',
                                                        'Velocidade Incompatível',
                                                              'Condutor Dormindo',
                                                    'Falta de Atenção à Condução',
                                                                 'Defeito na Via',
                                                             'Ingestão de Álcool',
                                             'Não guardar distância de segurança',
                                                             'Pista Escorregadia',
                                                   'Falta de Atenção do Pedestre',
                              'Desobediência às normas de trânsito pelo condutor',
                                                          'Fenômenos da Natureza',
                                                               'Animais na Pista',
                                                         'Ultrapassagem Indevida',
                                                                     'Mal Súbito',
                                         'Carga excessiva e/ou mal acondicionada',
                                       'Objeto estático sobre o leito carroçável',
                                        'Avarias e/ou desgaste excessivo no pneu',
                                  'Sinalização da via insuficiente ou inadequada',
 'Deficiência ou não Acionamento do Sistema de Iluminação/Sinalização do Veículo',
                                                      'Restrição de Visibilidade',
                                            'Ingestão de Substâncias Psicoativas',
                                       'Reação tardia ou ineficiente do condutor',
                                                               'Agressão Externa',
                              'Desobediência às normas de trânsito pelo pedestre',
                  'Ingestão de álcool e/ou substâncias psicoativas pelo pedestre',
                                               'Ingestão de álcool pelo condutor',
                                 'Acumulo de areia ou detritos sobre o pavimento',
                                                                'Curva acentuada',
                                       'Desrespeitar a preferência no cruzamento',
                                                       'Pedestre andava na pista',
                              'Ingestão de substâncias psicoativas pelo condutor',
                                           'Demais falhas mecânicas ou elétricas',
                                                         'Transitar na contramão',
                                                              'Pista em desnível',
                 'Ingestão de álcool ou de substâncias psicoativas pelo pedestre',
                                                 'Ausência de reação do condutor',
                                                                          'Chuva',
                                                               'Pista esburacada',
                                                                 'Obras na pista',
                                                    'Manobra de mudança de faixa',
                                              'Acumulo de óleo sobre o pavimento',
                        'Condutor desrespeitou a iluminação vermelha do semáforo',
                                                        'Condutor usando celular',
                                                        'Acostamento em desnível',
                                                             'Conversão proibida',
                      'Acessar a via sem observar a presença dos outros veículos',
                               'Deficiência do Sistema de Iluminação/Sinalização',
                                                           'Falta de acostamento',
                                                         'Mal súbito do condutor',
                                              'Acumulo de água sobre o pavimento',
                       'Condutor deixou de manter distância do veículo da frente',
                                                  'Entrada inopinada do pedestre',
                                                        'Ausência de sinalização',
                                                       'Transitar no acostamento',
                          'Trafegar com motocicleta (ou similar) entre as faixas',
                                                           'Demais falhas na via',
                                         'Pedestre cruzava a pista fora da faixa',
                                                              'Frear bruscamente',
                                          'Afundamento ou ondulação no pavimento',
                                                                         'Fumaça',
                                          'Estacionar ou parar em local proibido',
                                                          'Iluminação deficiente',
                                                               'Acesso irregular',
                                                   'Demais Fenômenos da natureza',
                                                           'Problema com o freio',
           'Falta de elemento de contenção que evite a saída do leito carroçável',
                                                               'Retorno proibido',
                                                               'Obstrução na via',
                                                              'Desvio temporário',
   'Área urbana sem a presença de local apropriado para a travessia de pedestres',
                                                    'Sinalização mal posicionada',
                                                           'Semáforo com defeito',
                                                              'Declive acentuado',
                                    'Faixas de trânsito com largura insuficiente',
                                  'Restrição de visibilidade em curvas verticais',
                                                                        'Neblina',
                                'Restrição de visibilidade em curvas horizontais',
                                                          'Problema na suspensão',
                                                            'Participar de racha',
                                                           'Modificação proibida',
                                                           'Transitar na calçada',
                                                            'Faróis desregulados',
                                                'Sistema de drenagem ineficiente',
                                             'Redutor de velocidade em desacordo',
                          'Deixar de acionar o farol da motocicleta (ou similar)',
                                                          'Sinalização encoberta',
                                                'Obstrução Via tentativa Assalto',
                                                       'Transitar no Acostamento',
                                                           'Suicídio (presumido)',
                                          'Transtornos Mentais (exceto suicidio)',
                         'Pedestre - Ingestão de álcool/ substâncias psicoativas']
Length: 91, dtype: str

A causa do acidente é uma variável **categórica** e possui 91 categorias.

In [5]:
df["tipo_acidente"].unique()

<StringArray>
[               'Colisão traseira',       'Saída de leito carroçável',
                 'Colisão frontal',                 'Colisão lateral',
     'Colisão com objeto estático',                      'Tombamento',
 'Colisão com objeto em movimento',           'Derramamento de carga',
       'Atropelamento de Pedestre',             'Colisão transversal',
                        'Incêndio',                     'Capotamento',
         'Atropelamento de Animal',                   'Engavetamento',
                 'Danos eventuais',    'Queda de ocupante de veículo',
              'Colisão com objeto',                               nan,
   'Colisão lateral mesmo sentido',                'Eventos atípicos',
  'Colisão lateral sentido oposto',    'Sinistro pessoal de trânsito']
Length: 22, dtype: str

O tipo do acidente é uma variável **categórica** e possui 22 categorias.

In [6]:
df["fase_dia"].unique()

<StringArray>
['Plena Noite', 'Amanhecer', 'Pleno dia', 'Anoitecer']
Length: 4, dtype: str

A fase do dia é uma variável **categórica** e possui 4 categorias.

In [7]:
df["condicao_metereologica"].unique()

<StringArray>
[       'Céu Claro',   'Garoa/Chuvisco',          'Nublado',
              'Sol',            'Chuva', 'Nevoeiro/Neblina',
         'Ignorado',            'Vento',          'Granizo',
             'Neve']
Length: 10, dtype: str

A condição meteorológica é uma variável **categórica** e possui 10 caategorias.

In [8]:
df["classificacao_acidente"].unique()

<StringArray>
['Com Vítimas Feridas', 'Com Vítimas Fatais', nan, 'Sem Vítimas']
Length: 4, dtype: str

A classificação do acidente é uma variável **categórica** e possui 4 categorias.

In [9]:
df["feridos_graves"].unique()

array([ 0,  1,  2,  3,  4,  9,  6,  5,  7, 10,  8, 16, 21, 28, 17, 12, 22,
       13, 15, 18, 20, 11, 19, 23, 26, 31, 14, 29, 24, 30])

Feridos graves é uma variável **numérica** e varia de 0 a 30 no dataset.

In [10]:
df["mortos"].unique()

array([ 0,  1,  2,  3,  4,  5,  6,  8, 21,  7, 11,  9, 10, 13, 12, 19, 23])

Mortos é uma variável **numérica** e varia de 0 a 23 no dataset.

## Verificando a qualidade dos dados

In [11]:
# Verificando se há duplicatas

df.duplicated().sum()

np.int64(0)

In [12]:
# Se houver dados duplicados, verificamos quais são:

df[df.duplicated()]

Empty DataFrame
Columns: [id, data_inversa, dia_semana, horario, uf, br, km, municipio, causa_acidente, tipo_acidente, classificacao_acidente, fase_dia, sentido_via, condicao_metereologica, tipo_pista, tracado_via, uso_solo, pessoas, mortos, feridos_leves, feridos_graves, ilesos, ignorados, feridos, veiculos, latitude, longitude, regional, delegacia, uop]
Index: []

[0 rows x 30 columns]

Conclusão 1: não há duplicatas no dataset analisado.

In [ ]:
# Verificando se há valores faltantes

df.isnull().sum()

id                          0
data_inversa                0
dia_semana                  0
horario                     0
uf                          0
br                          0
km                          0
municipio                   0
causa_acidente              0
tipo_acidente              41
classificacao_acidente      9
fase_dia                    0
sentido_via                 0
condicao_metereologica      0
tipo_pista                  0
tracado_via                 0
uso_solo                    0
pessoas                     0
mortos                      0
feridos_leves               0
feridos_graves              0
ilesos                      0
ignorados                   0
feridos                     0
veiculos                    0
latitude                    0
longitude                   0
regional                   25
delegacia                 203
uop                       379
dtype: int64

## Limpeza do conjunto de dados